;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-delete-forward
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        comment-line
        delete-horizontal-space
        forward-sexp
        ignore
        indent-for-tab-command
        kill-region
        kill-visual-line
        list-buffers
        lsp-ui-doc--handle-mouse-movement
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-cycle
        org-delete-char
        org-end-of-line
        org-kill-line
        org-latex-preview
        org-metadown
        org-metaleft
        org-metaright
        org-metaup
        org-self-insert-command
        org-shiftcontrolright
        org-yank
        phi-autopair-delete-backward
        phi-autopair-delete-forward
        sis--prefix-override-handler
        wdired--self-insert
        wdired-abort-changes
        ))

(setq mc/cmds-to-run-once
      '(
        electric-pair-delete-pair
        mouse-drag-mode-line
        ))
