;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-delete-forward
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        comment-line
        crux-eval-and-replace
        dap-breakpoint-toggle
        delete-horizontal-space
        eval-last-sexp
        forward-sexp
        ibuffer-do-delete
        ibuffer-mark-forward
        ignore
        indent-for-tab-command
        kill-region
        kill-visual-line
        kmacro-start-macro-or-insert-counter
        list-buffers
        lsp-ui-doc--handle-mouse-movement
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-latex-preview
        org-metadown
        org-metaleft
        org-metaright
        org-metaup
        org-return
        org-return-and-maybe-indent
        org-self-insert-command
        org-shiftcontrolright
        org-shiftright
        org-yank
        phi-autopair-delete-backward
        phi-autopair-delete-forward
        sgml-slash
        sis--prefix-override-handler
        sp-backward-sexp
        sp-forward-sexp
        vhdl-electric-space
        wdired--self-insert
        wdired-abort-changes
        ))

(setq mc/cmds-to-run-once
      '(
        rime--backspace
        toggle-input-method
        ))
